//
// ICONS (100-149)
//
#define IDI_APP_ICON            100
#define IDI_ICON_HOME           101
#define IDI_ICON_SETTING        102
#define IDI_ICON_ABOUT          103


//
// STRING IDS (200-299)
//
#define STRING_IDS_BASE         200
#define IDS_MAIN_CLASS_NAME     (STRING_IDS_BASE + 0)


//
// SIDEBAR (300-349)
//
#define SIDEBAR_BASE            300

#define IDC_SIDEBAR             (SIDEBAR_BASE + 0)

#define IDS_SIDEBAR_HOME_TEXT   (SIDEBAR_BASE + 1)
#define IDS_SIDEBAR_SETTINGS_TEXT (SIDEBAR_BASE + 2)
#define IDS_SIDEBAR_FOOTER_TEXT (SIDEBAR_BASE + 3)
#define IDS_SIDEBAR_ABOUT_TEXT  (SIDEBAR_BASE + 4)

#define IDC_SIDEBAR_HOME        (SIDEBAR_BASE + 20)
#define IDC_SIDEBAR_SETTING     (SIDEBAR_BASE + 21)
#define IDC_SIDEBAR_ABOUT       (SIDEBAR_BASE + 22)


//
// SETTINGS PAGE CONTROLS (500-599)
//
#define SETTINGS_PAGE_CONTROLS  400

#define IDC_EDIT_TEST_EMAIL     (SETTINGS_PAGE_CONTROLS + 0)
#define IDC_SLIDER_THREADS      (SETTINGS_PAGE_CONTROLS + 1)
#define IDC_SLIDER_RETRIES      (SETTINGS_PAGE_CONTROLS + 2)
#define IDC_LBL_THREAD_PREVIEW  (SETTINGS_PAGE_CONTROLS + 3)
#define IDC_LBL_RETRY_PREVIEW   (SETTINGS_PAGE_CONTROLS + 4)
#define IDC_EDIT_TELEGRAM_TOKEN (SETTINGS_PAGE_CONTROLS + 5)
#define IDC_EDIT_TELEGRAM_ID    (SETTINGS_PAGE_CONTROLS + 6)
#define IDC_EDIT_SAVE_FILE      (SETTINGS_PAGE_CONTROLS + 7)
#define IDC_BTN_TEST_TELEGRAM   (SETTINGS_PAGE_CONTROLS + 8)
#define IDC_BTN_SAVE_SETTINGS   (SETTINGS_PAGE_CONTROLS + 9)
#define IDC_COMBO_THEME_MODE    (SETTINGS_PAGE_CONTROLS + 10)
#define IDC_COMBO_COLOR_SCHEME  (SETTINGS_PAGE_CONTROLS + 11)


#define SETTINGS_STRINGS_BASE 500


#define IDS_SETTINGS_GROUP_GENERAL        (SETTINGS_STRINGS_BASE + 0)
#define IDS_SETTINGS_LABEL_EMAIL          (SETTINGS_STRINGS_BASE + 1)
#define IDS_SETTINGS_LABEL_THREAD         (SETTINGS_STRINGS_BASE + 2)
#define IDS_SETTINGS_LABEL_RETRY          (SETTINGS_STRINGS_BASE + 3)
#define IDS_SETTINGS_LABEL_SAVEFILE       (SETTINGS_STRINGS_BASE + 4)

#define IDS_SETTINGS_GROUP_TELEGRAM       (SETTINGS_STRINGS_BASE + 5)
#define IDS_SETTINGS_TELEGRAM_TOKEN_CUE   (SETTINGS_STRINGS_BASE + 6)
#define IDS_SETTINGS_TELEGRAM_CHAT_CUE    (SETTINGS_STRINGS_BASE + 7)

#define IDS_SETTINGS_GROUP_APPEARANCE     (SETTINGS_STRINGS_BASE + 8)
#define IDS_SETTINGS_THEME_MODE           (SETTINGS_STRINGS_BASE + 9)
#define IDS_SETTINGS_COLOR_SCHEME         (SETTINGS_STRINGS_BASE + 10)

#define IDS_SETTINGS_BTN_TEST_TELEGRAM    (SETTINGS_STRINGS_BASE + 11)
#define IDS_SETTINGS_BTN_SAVE             (SETTINGS_STRINGS_BASE + 12)

#define IDS_SETTINGS_THREAD_PREVIEW_FMT   (SETTINGS_STRINGS_BASE + 13)
#define IDS_SETTINGS_RETRY_PREVIEW_FMT    (SETTINGS_STRINGS_BASE + 14)

#define IDS_THEME_MODE_DARK               (SETTINGS_STRINGS_BASE + 15)
#define IDS_THEME_MODE_LIGHT              (SETTINGS_STRINGS_BASE + 16)
#define IDS_THEME_MODE_SYSTEM             (SETTINGS_STRINGS_BASE + 17)
#define IDS_SETTINGS_LABEL_TEST_EMAIL	  (SETTINGS_STRINGS_BASE + 18)

//
// DARK THEMES (600-699)
//
#define THEME_DARK_BASE 600

#define IDS_THEME_DARK_DEFAULT          (THEME_DARK_BASE + 0)
#define IDS_THEME_DARK_DRACULA          (THEME_DARK_BASE + 1)
#define IDS_THEME_DARK_NORD             (THEME_DARK_BASE + 2)
#define IDS_THEME_DARK_SOLARIZED        (THEME_DARK_BASE + 3)
#define IDS_THEME_DARK_ONEDARKPRO       (THEME_DARK_BASE + 4)
#define IDS_THEME_DARK_GITHUB           (THEME_DARK_BASE + 5)
#define IDS_THEME_DARK_MATERIAL         (THEME_DARK_BASE + 6)
#define IDS_THEME_DARK_NIGHTOWL         (THEME_DARK_BASE + 7)
#define IDS_THEME_DARK_COBALT2          (THEME_DARK_BASE + 8)
#define IDS_THEME_DARK_AYUMIRAGE        (THEME_DARK_BASE + 9)
#define IDS_THEME_DARK_GRUVBOX          (THEME_DARK_BASE + 10)
#define IDS_THEME_DARK_SYNTHWAVE        (THEME_DARK_BASE + 11)
#define IDS_THEME_DARK_SHADESOFPURPLE   (THEME_DARK_BASE + 12)
#define IDS_THEME_DARK_TOKYONIGHT       (THEME_DARK_BASE + 13)
#define IDS_THEME_DARK_OCEANICNEXT      (THEME_DARK_BASE + 14)
#define IDS_THEME_DARK_CITYLIGHTS       (THEME_DARK_BASE + 15)
#define IDS_THEME_DARK_KIMBIE           (THEME_DARK_BASE + 16)
#define IDS_THEME_DARK_PANDA            (THEME_DARK_BASE + 17)
#define IDS_THEME_DARK_MONOKAI          (THEME_DARK_BASE + 18)
#define IDS_THEME_DARK_GRUVBOXMATERIAL  (THEME_DARK_BASE + 19)
#define IDS_THEME_DARK_ARC              (THEME_DARK_BASE + 20)
#define IDS_THEME_DARK_OBSIDIAN         (THEME_DARK_BASE + 21)
#define IDS_THEME_DARK_DARCULA          (THEME_DARK_BASE + 22)
#define IDS_THEME_DARK_FLAT             (THEME_DARK_BASE + 23)
#define IDS_THEME_DARK_CHALLENGERDEEP   (THEME_DARK_BASE + 24)
#define IDS_THEME_DARK_CYBERPUNK        (THEME_DARK_BASE + 25)
#define IDS_THEME_DARK_MOONLIGHT        (THEME_DARK_BASE + 26)
#define IDS_THEME_DARK_OMNI             (THEME_DARK_BASE + 27)
#define IDS_THEME_DARK_SPACEGRAY        (THEME_DARK_BASE + 28)
#define IDS_THEME_DARK_MIDNIGHT         (THEME_DARK_BASE + 29)
#define IDS_THEME_DARK_FOREST           (THEME_DARK_BASE + 30)
#define IDS_THEME_DARK_BLOODMOON        (THEME_DARK_BASE + 31)
#define IDS_THEME_DARK_AURORA           (THEME_DARK_BASE + 32)
#define IDS_THEME_DARK_STEALTH          (THEME_DARK_BASE + 33)
#define IDS_THEME_DARK_DEEPPURPLE       (THEME_DARK_BASE + 34)
#define IDS_THEME_DARK_DESERT           (THEME_DARK_BASE + 35)
#define IDS_THEME_DARK_DEEPSEA          (THEME_DARK_BASE + 36)
#define IDS_THEME_DARK_SLATE            (THEME_DARK_BASE + 37)
#define IDS_THEME_DARK_SHADOW           (THEME_DARK_BASE + 38)
#define IDS_THEME_DARK_HACKER_TERMINAL  (THEME_DARK_BASE + 39)
#define IDS_THEME_DARK_MATRIX           (THEME_DARK_BASE + 40)
#define IDS_THEME_DARK_NEONCORE         (THEME_DARK_BASE + 41)
#define IDS_THEME_DARK_RETROTERMINAL    (THEME_DARK_BASE + 42)
#define IDS_THEME_DARK_ICEHACK          (THEME_DARK_BASE + 43)


//
// LIGHT THEMES (700-799)
//
#define THEME_LIGHT_BASE 700

#define IDS_THEME_LIGHT_SOLARIZED       (THEME_LIGHT_BASE + 0)
#define IDS_THEME_LIGHT_GITHUB          (THEME_LIGHT_BASE + 1)
#define IDS_THEME_LIGHT_VS              (THEME_LIGHT_BASE + 2)
#define IDS_THEME_LIGHT_ONE             (THEME_LIGHT_BASE + 3)
#define IDS_THEME_LIGHT_AYU             (THEME_LIGHT_BASE + 4)
#define IDS_THEME_LIGHT_GRUVBOX         (THEME_LIGHT_BASE + 5)
#define IDS_THEME_LIGHT_NORD            (THEME_LIGHT_BASE + 6)
#define IDS_THEME_LIGHT_DRACULASOFT     (THEME_LIGHT_BASE + 7)
#define IDS_THEME_LIGHT_MATERIAL        (THEME_LIGHT_BASE + 8)
#define IDS_THEME_LIGHT_PAPERCOLOR      (THEME_LIGHT_BASE + 9)
#define IDS_THEME_LIGHT_ATOM            (THEME_LIGHT_BASE + 10)
#define IDS_THEME_LIGHT_CITYLIGHTS      (THEME_LIGHT_BASE + 11)
#define IDS_THEME_LIGHT_VSCODEMODERN    (THEME_LIGHT_BASE + 12)
#define IDS_THEME_LIGHT_TOMORROW        (THEME_LIGHT_BASE + 13)
#define IDS_THEME_LIGHT_PANDA           (THEME_LIGHT_BASE + 14)
#define IDS_THEME_LIGHT_ESPRESSO        (THEME_LIGHT_BASE + 15)
#define IDS_THEME_LIGHT_MONOKAI         (THEME_LIGHT_BASE + 16)
#define IDS_THEME_LIGHT_HIGHCONTRAST    (THEME_LIGHT_BASE + 17)
#define IDS_THEME_LIGHT_FLATWHITE       (THEME_LIGHT_BASE + 18)
#define IDS_THEME_LIGHT_CLASSIC         (THEME_LIGHT_BASE + 19)
#define IDS_THEME_LIGHT_TOMORROWBRIGHT  (THEME_LIGHT_BASE + 20)
#define IDS_THEME_LIGHT_SOLARIZEDHIGH   (THEME_LIGHT_BASE + 21)
#define IDS_THEME_LIGHT_QUIET           (THEME_LIGHT_BASE + 22)
#define IDS_THEME_LIGHT_ATOMONESOFT     (THEME_LIGHT_BASE + 23)
#define IDS_THEME_LIGHT_PAPER           (THEME_LIGHT_BASE + 24)
#define IDS_THEME_LIGHT_CLASSICMAC      (THEME_LIGHT_BASE + 25)
#define IDS_THEME_LIGHT_MINIMAL         (THEME_LIGHT_BASE + 26)
#define IDS_THEME_LIGHT_FROST           (THEME_LIGHT_BASE + 27)
#define IDS_THEME_LIGHT_CREAM           (THEME_LIGHT_BASE + 28)
#define IDS_THEME_LIGHT_SANDSTORM       (THEME_LIGHT_BASE + 29)
#define IDS_THEME_LIGHT_MINT            (THEME_LIGHT_BASE + 30)
#define IDS_THEME_LIGHT_PEACH           (THEME_LIGHT_BASE + 31)
#define IDS_THEME_LIGHT_LAVENDER        (THEME_LIGHT_BASE + 32)
#define IDS_THEME_LIGHT_SAND            (THEME_LIGHT_BASE + 33)
#define IDS_THEME_LIGHT_ICE             (THEME_LIGHT_BASE + 34)
#define IDS_THEME_LIGHT_MEADOW          (THEME_LIGHT_BASE + 35)
#define IDS_THEME_LIGHT_CORAL           (THEME_LIGHT_BASE + 36)
#define IDS_THEME_LIGHT_SPRING          (THEME_LIGHT_BASE + 37)
#define IDS_THEME_LIGHT_SKY             (THEME_LIGHT_BASE + 38)
#define IDS_THEME_LIGHT_CHOCOLATE       (THEME_LIGHT_BASE + 39)
#define IDS_THEME_LIGHT_HACKER_TERMINAL (THEME_LIGHT_BASE + 40)
#define IDS_THEME_LIGHT_MATRIX          (THEME_LIGHT_BASE + 41)
#define IDS_THEME_LIGHT_NEONCORE        (THEME_LIGHT_BASE + 42)
#define IDS_THEME_LIGHT_RETROTERMINAL   (THEME_LIGHT_BASE + 43)
#define IDS_THEME_LIGHT_ICEHACK         (THEME_LIGHT_BASE + 44)


#define HOME_STRINGS_BASE        800

#define IDS_HOME_BTN_UPLOAD      (HOME_STRINGS_BASE + 0)
#define IDS_HOME_BTN_START       (HOME_STRINGS_BASE + 1)

#define IDS_HOME_LBL_COMBOS      (HOME_STRINGS_BASE + 2)
#define IDS_HOME_LBL_VALID       (HOME_STRINGS_BASE + 3)
#define IDS_HOME_LBL_FAILED      (HOME_STRINGS_BASE + 4)
#define IDS_HOME_LBL_DELIVERY    (HOME_STRINGS_BASE + 5)

#define IDS_HOME_COL_HOST        (HOME_STRINGS_BASE + 6)
#define IDS_HOME_COL_EMAIL       (HOME_STRINGS_BASE + 7)
#define IDS_HOME_COL_PORT        (HOME_STRINGS_BASE + 8)
#define IDS_HOME_COL_PASS        (HOME_STRINGS_BASE + 9)
#define IDS_HOME_COL_STATUS      (HOME_STRINGS_BASE + 10)
#define IDS_HOME_COL_DELIVERY    (HOME_STRINGS_BASE + 11)

#define IDS_HOME_CONSOLE_INIT    (HOME_STRINGS_BASE + 12)



#define HOMEPAGE_PAGE_CONTROLS  900

#define IDC_BTN_UPLOAD      (HOMEPAGE_PAGE_CONTROLS + 0)
#define IDC_BTN_START       (HOMEPAGE_PAGE_CONTROLS + 1)
#define IDC_LBL_COMBOS      (HOMEPAGE_PAGE_CONTROLS + 2)
#define IDC_LBL_VALID       (HOMEPAGE_PAGE_CONTROLS + 3)
#define IDC_LBL_FAILED      (HOMEPAGE_PAGE_CONTROLS + 4)
#define IDC_LBL_DELIVERY    (HOMEPAGE_PAGE_CONTROLS + 5)
#define IDC_LISTVIEW_MAIN   (HOMEPAGE_PAGE_CONTROLS + 6)
#define IDC_CONSOLE_LOG     (HOMEPAGE_PAGE_CONTROLS + 7)


#define WM_WORKER_LOG       (WM_USER + 1) // wParam: (char*) message
#define WM_WORKER_RESULT    (WM_USER + 2) // lParam: (RESULT_DATA*) structure
#define WM_WORKER_FINISHED  (WM_USER + 3)
#define WM_WORKER_PROGRESS  (WM_USER + 4)